NAME = input("ENTER YOUR NAME:\n")
AGE = input("ENTER YOUR AGE:\n")
GENDER = input("ENTER YOUR GENDER:\n")
OCCUPATION = input("ENTER YOUR OCCUPATION:\a")
print(NAME)
print(AGE)
print(GENDER)
print(OCCUPATION)
